### ISSUE TITLE
Doesn't ban on other server

### ISSUE THREAD

**Issue by NormalOcean6686** [adeynes/cucumber#13]
Ban system doesn't check the mysql to see if the player was ban when they were ban on other server on the same mysql

**Comment by adeynes** [comment]
If you restart the other server, they're banned though, right?

**Comment by NormalOcean6686** [comment]
Yes but can u make it be able to do it without restarting the server?

**Comment by adeynes** [comment]
Yep, I'm working on an update right now. This will come with 2.0.
