### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by mastergaminglord** [adeynes/cucumber#15]
when i try to start my server with cucumber installed it get this error

2020-06-18 [16:49:28] [Server thread/CRITICAL]: adeynes\cucumber\libs\poggit\libasynql\SqlError: "SQL CONNECT error: Connection refused" (EXCEPTION) in "plugins/cucumber.phar/src/adeynes/cucumber/libs/poggit/libasynql/libasynql" at line 133

is this fixable

**Comment by adeynes** [comment]
This is a problem on your end. You haven't set up the connection correctly (probably incorrect username/password in config.yml).

**Comment by mastergaminglord** [comment]
also extra info I have tried this plugin on its own with no other plugin and it the same problem occured

**Comment by mastergaminglord** [comment]
in the config.yml folder what do I type in the password thing

**Comment by adeynes** [comment]
> in the config.yml folder what do I type in the password thing

You type the password for the MySQL user

**Comment by mastergaminglord** [comment]
the plugin assumes you automatically have MySQL but idk if i do or not

**Comment by mastergaminglord** [comment]
which is why i am confused

**Comment by adeynes** [comment]
Yes, the plugin requires MySQL. I haven't developed it with other systems in mind, although SQLite might come in the future.

**Comment by mastergaminglord** [comment]
um where do you download MySQL

**Comment by adeynes** [comment]
Windows or Linux?

**Comment by mastergaminglord** [comment]
no i mean the website

and also are u able to ban someone for permanent off the server or is it only temp ban

**Comment by adeynes** [comment]
> no i mean the website

I mean, are you on Linux or on Windows?

> and also are u able to ban someone for permanent off the server or is it only temp ban

Both

**Comment by mastergaminglord** [comment]
im on windows yes
 if its perm ban is it -1 in the duratation

**Comment by adeynes** [comment]
https://dev.mysql.com/downloads/installer/
You might also want to download phpmyadmin to manager your database here: https://www.phpmyadmin.net/downloads/

For perm ban you don't put a duration at all, ex. /ban mastergaminglord (if I wanted to ban you for 1 month 15 days I'd do /ban mastergaminglord -d 1M15d)

**Comment by mastergaminglord** [comment]
this is taking a while are u trying to find the download links

**Comment by mastergaminglord** [comment]
ohh i see it now

**Comment by mastergaminglord** [comment]
thx for your help i will get back to you if i need help with the database btw im using aternos

also the reason why i installed this plugin in the first place was because the kicked and banned by admin messages are really annoying
thx for your help

**Comment by adeynes** [comment]
You're welcome, I hope you can figure out. Don't be afraid to google stuff if you can't figure something out, it's not necessarily intuitive at first. What you need to do is create a database with phpmyadmin and a user that goes with it, and put all that in config.yml

I hope you enjoy the plugin

**Comment by adeynes** [comment]
Wait, if you're using Aternos installing MySQL on your computer won't do anything. Does Aternos not have MySQL databases?

**Comment by adeynes** [comment]
Seems like Aternos doesn't offer MySQL databases. In that case you might want to use this https://www.freesqldatabase.com/ and put the IP of the database along with username, password, etc in config.yml

**Comment by mastergaminglord** [comment]
thx for that but there is a problem

it says I need a oracle account and I press sign up and it says I need a work phone and things so idk

**Comment by adeynes** [comment]
I'm sorry but I can't help you with this, I haven't used MySQL on Windows and Github isn't tech support. You'll have to ask somewhere that actually does support for this kind of stuff

**Comment by mastergaminglord** [comment]
its fine

**Comment by mastergaminglord** [comment]
im actually really upset now every time i try to click the link it sends me to a blank page with error and i think its blocked my ip address permanently

**Comment by mastergaminglord** [comment]
adeynes i have a question

am I able to unban myself I did /ban through the console
