### ISSUE TITLE
this is not an issue just a question

### ISSUE THREAD

**Issue by mastergaminglord** [adeynes/cucumber#16]
how do I get the ip address to the server when im using MYSQL on my computer

**Comment by mastergaminglord** [comment]
in the config.yml what do you put for the schema to replace cucumber

**Comment by adeynes** [comment]
You put the name of the database. You'd put your IP address but you'd need to have everything portforwarded. Really what you need is server and database on the same machine for something like this.
Please ask in a Discord or something of the sort next time, Github issues isn't for questions
