### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by MegaLordXx** [adeynes/cucumber#21]
is it possible to use SQLite to get the plugin working

and what do you do if u want to use SQLite in the config.yml

and finally how to u change the players stable option

**Comment by adeynes** [comment]
The plugin doesn't support SQLite, sorry. It might come in a future version. The only database option right now is MySQL. What do you mean by the "players stable option"?

**Comment by MegaLordXx** [comment]
on one of the previous issues i saw u mention somthing to do with players stable
