### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by MegaLordXx** [adeynes/cucumber#22]
in the config.yml do u have to create a schema/database called cucumber

also if u want cucumber to access your MySQL server do u need phpmyadmin

**Comment by adeynes** [comment]
You need a MySQL database for cucumber. It doesn't have to be called `cucumber`, you just need to put its name in `schema` in `config.yml`.
You don't need phpmyadmin to access you MySQL server, it's just a convenient way to manage it without using the command line directly.

**Comment by MegaLordXx** [comment]
ok thats great
thank u
