### ISSUE TITLE
The 'cucumber plugin had a problem during execution.

### ISSUE THREAD

**Issue by gxserrao** [adeynes/cucumber#34]
The log indicates that there was a SQL CONNECT error (Line 163):

163| 2021-01-05 [13:33:11] [Server thread/CRITICAL]: adeynes\cucumber\libs\poggit\libasynql\SqlError: "SQL CONNECT error: Connection refused" (EXCEPTION) in "plugins/cucumber.phar/src/adeynes/cucumber/libs/poggit/libasynql/libasynql" at line 141
--
164 | 2021-01-05 [13:33:11] [Server thread/CRITICAL]: #0 plugins/cucumber.phar/src/adeynes/cucumber/Cucumber(141): adeynes\cucumber\libs\poggit\libasynql\libasynql::create(string[33] object(adeynes\cucumber\Cucumber), array[3], array[1])
165 | 2021-01-05 [13:33:11] [Server thread/CRITICAL]: #1 plugins/cucumber.phar/src/adeynes/cucumber/Cucumber(70): adeynes\cucumber\Cucumber->initDatabase()
166 | 2021-01-05 [13:33:11] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/PluginBase(116): adeynes\cucumber\Cucumber->onEnable()
167 | 2021-01-05 [13:33:11] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
168 | 2021-01-05 [13:33:11] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/Server(1786): pocketmine\plugin\PluginManager->enablePlugin(string[33] object(adeynes\cucumber\Cucumber))
169 | 2021-01-05 [13:33:11] [Server thread/CRITICAL]: #5 pmsrc/src/pocketmine/Server(1772): pocketmine\Server->enablePlugin(string[33] object(adeynes\cucumber\Cucumber))
170 | 2021-01-05 [13:33:11] [Server thread/CRITICAL]: #6 pmsrc/src/pocketmine/Server(1585): pocketmine\Server->enablePlugins(integer 1)
171 | 2021-01-05 [13:33:11] [Server thread/CRITICAL]: #7 pmsrc/src/pocketmine/PocketMine(272): pocketmine\Server->__construct(string[23] object(BaseClassLoader), string[35] object(pocketmine\utils\MainLogger), string[8] /server/, string[16] /server/plugins/)
172 | 2021-01-05 [13:33:11] [Server thread/CRITICAL]: #8 pmsrc/src/pocketmine/PocketMine(302): pocketmine\server()
173 | 2021-01-05 [13:33:11] [Server thread/CRITICAL]: #9 pmsrc(11): require(string[56] phar:///server/server.phar/src/pocketmine/PocketMine.php)

Here's the full log link: https://mclo.gs/PxWzlMi#L163

I hope this can contribute to improvements in the plugin
Regards

**Comment by adeynes** [comment]
As the error says, the connection was refused. This is either a setup error (didn't enter the correct MySQL credentials in `config.yml`), or an error with your host.
