### ISSUE TITLE
Cucumber ERROR

### ISSUE THREAD

**Issue by MarcoGYTV2** [adeynes/cucumber#36]
Hi there today is 3/27/2021 i found many errors with the plugin in my console here is the screenshot of the error please fix it, OR tell me how to fix it this plugin is awesome by the way.

[CLICK HERE FOR THE ERROR PNG!](https://media.discordapp.net/attachments/801827201427177502/825453716865286165/unknown.png)

**Comment by adeynes** [comment]
This is not an error with the plugin. You entered the wrong MySQL credentials in `config.yml`.
